version: 2.1
orbs:
  codecov: codecov/codecov@1.1.1
jobs:
  build:
    docker:
      - image: circleci/node:15.14.0
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - codecov/upload:
          file: tests/coverage/*.json
workflows:
  build:
    jobs:
      - build
